SELECT CONCAT('JOSE','PEREZ') FROM DUAL;

SELECT 'JOSE'||' '||'PEREZ'||' '||'GUZMAN' FROM DUAL;

SELECT 'JOSE'||'/'||'PEREZ'||'/'||'GUZMAN' FROM DUAL;


----------------------------------------------------

SELECT SUBSTR('JOSE PEREZ',6,5) FROM DUAL;

SELECT SUBSTR('JOSE PEREZ',1,4) FROM DUAL;

SELECT LENGTH('PEPE PEREZ') FROM DUAL;

SELECT ENAME, LENGTH(ENAME) FROM EMP;

SELECT INSTR('PEPE PEREZ','PER') FROM DUAL; 

SELECT INSTR('PEPE PEREZ',' ') FROM DUAL; 

----------------------------------------------------
SELECT LPAD('PEPE PEREZ',20,'-') FROM DUAL; 

SELECT RPAD('PEPE PEREZ',20,'-') FROM DUAL; 

SELECT RPAD(LPAD('PEPE PEREZ',20,'-'),30,'-') FROM DUAL; 




-------------------------------------------
SELECT  8*7-12/6 FROM DUAL; 

SELECT ENAME, ROUND(SAL/9,3) FROM EMP WHERE SAL>1500;

SELECT MOD(SAL,2) FROM EMP WHERE SAL>500;

SELECT ROUND(SAL/7,1), TRUNC(SAL/3, 2) FROM EMP;


-------------------------------------------

SELECT 
	CURRENT_DATE, 
	ADD_MONTHS(CURRENT_DATE,4), 
	NEXT_DAY(CURRENT_DATE,'JUEVES') 
FROM DUAL;

SELECT 
ROUND(MONTHS_BETWEEN(CURRENT_DATE,'24-09-1994'),1) 
FROM DUAL;

SELECT 
ROUND(MONTHS_BETWEEN('24-05-1994','01-01-2012'),2) 
FROM DUAL;


-------------------------------------------

SELECT TO_CHAR(SYSDATE,'DAY,DD')||'de'|| TO_CHAR(SYSDATE,'MONTH')||'de'||TO_CHAR(SYSDATE,'YYYY') FROM DUAL;

SELECT * FROM EMP WHERE hiredate BETWEEN '16/12/1980' AND '27/09/1981';

SELECT TO_CHAR(TO_DATE('01012001'),'MONTH') FROM DUAL;




