CREATE TABLE ALUMNOS(
	ID_ALUMNO INTEGER NOT NULL CONSTRAINT PK_ALUMNOS PRIMARY KEY,
	NOMBRE VARCHAR2(25),
	APELLIDO VARCHAR2(25),
	FECHA_NAC DATE
);


CREATE TABLE CURSOS(
	ID_CURSO INTEGER NOT NULL CONSTRAINT PK_CURSOS PRIMARY KEY,
	NOMBRE_CURSO VARCHAR2(25),
	CATEGORIA VARCHAR2(25)  CONSTRAINT NN_CATEGORIA NOT NULL,
	DESCRIPCION VARCHAR2(50)
);

CREATE TABLE MATRICULA(
	ID_MATRICULA INTEGER NOT NULL CONSTRAINT PK_MATRICULA PRIMARY KEY,
	ID_ALUMNO INTEGER NOT NULL,
	CONSTRAINT FK_MATRICULA_ALUMNOS FOREIGN KEY(ID_ALUMNO) REFERENCES ALUMNOS(ID_ALUMNO),
	ID_CURSO INTEGER NOT NULL,
	CONSTRAINT FK_MATRICULA_CURSOS FOREIGN KEY(ID_CURSO) REFERENCES CURSOS(ID_CURSO),
	FEC_MAT DATE
);