CREATE TABLE PRODUCTO(
  COD_PRO CHAR(4) NOT NULL PRIMARY KEY,
  DESCRIP_PRO VARCHAR2(40) NOT NULL,
  PRECIO_PRO NUMBER(8,2) NOT NULL,
  STOCK_ACT_PRO NUMBER(8)  NOT NULL,
  STOCK_MIN_PRO NUMBER(8)  NOT NULL
);

DROP TABLE PRODUCTO;

CREATE TABLE PRODUCTO(
  COD_PRO CHAR(4) NOT NULL CONSTRAINTS PK_CODPRO PRIMARY KEY,
  DESCRIP_PRO VARCHAR2(40) NOT NULL,
  PRECIO_PRO NUMBER(8,2) NOT NULL,
  STOCK_ACT_PRO NUMBER(8)  NOT NULL,
  STOCK_MIN_PRO NUMBER(8)  NOT NULL
);


CREATE TABLE DISTRITO(
  COD_DIST CHAR(3) NOT NULL CONSTRAINTS PK_CODDIST PRIMARY KEY,
  DESCRIP_DIST VARCHAR(50) NOT NULL
);

CREATE TABLE CLIENTE(
  COS_CLI CHAR(6) NOT NULL CONSTRAINTS PK_CODCLI PRIMARY KEY,
  NOMBRES VARCHAR(50) NOT NULL,
  APE_PATER_CLI VARCHAR(50) NOT NULL,
  APE_MATER_CLI VARCHAR(50) NOT NULL,
  DIRECCION_CLI VARCHAR(50) NULL,
  TELEFONO_CLI VARCHAR(50) NULL,
  COD_DIST CHAR(3) NOT NULL,
  CONSTRAINT FK_CLIENTE_DISTRITO
  FOREIGN KEY(COD_DIST)
  REFERENCES DISTRITO(COD_DIST),
  CORREO_E VARCHAR(50) NULL
);

CREATE TABLE EMP(
  EMPNO NUMBER(4) NOT NULL,
  ENAME VARCHAR2(10),
  JOB VARCHAR2(9), 
  MGR NUMBER(4),
  HIREDATE DATE,
  SAL NUMBER(7,2), 
  COMM NUMBER(7,2), 
  DEPTNO NUMBER(2)
);

ALTER TABLE EMP ADD BONUS NUMBER(12,2);

DESCRIB EMP;

ALTER TABLE EMP ADD (DIRECCION VARCHAR2(50), TELEFONO CHAR(9));

ALTER TABLE EMP MODIFY BONUS NUMBER(9,2);

ALTER TABLE EMP RENAME COLUMN BONUS TO BONUS_EMP;

ALTER TABLE EMP EMP DROP COLUMN TELEFONO;

