--PREGUNTA 1


--PREGUNTA 2
CREATE TABLE ALUMNOS(
	ID_ALUMNO INTEGER NOT NULL CONSTRAINT PK_ALUMNOS PRIMARY KEY,
	NOMBRE VARCHAR2(25),
	APELLIDO VARCHAR2(25),
	FECHA_NAC DATE
);

CREATE TABLE CURSOS(
	ID_CURSO INTEGER NOT NULL CONSTRAINT PK_CURSOS PRIMARY KEY,
	NOMBRE_CURSO VARCHAR2(25),
	CATEGORIA VARCHAR2(25) NOT NULL,
	DESCRIPCION VARCHAR2(25)
);

CREATE TABLE MATRICULA(
	ID_MATRICULA INTEGER NOT NULL CONSTRAINT PK_MATRICULA PRIMARY KEY,
	ID_ALUMNO INTEGER NOT NULL PRIMARY KEY,
	ID_CURSO INTEGER NOT NULL PRIMARY KEY,
	FEC_MAT DATE
);

--PREGUNTA 3
--PREGUNTA 4
--PREGUNTA 5
--PREGUNTA 6
--PREGUNTA 7
--PREGUNTA 8
--PREGUNTA 9
--PREGUNTA 10