--PREGUNTA 1
SELECT * FROM DICTIONARY;
SELECT * FROM ALL_TABLES;

SELECT OWNER, ACCOUNT_STATUS, COUNT(OWNER) AS CANT_OBJS, CREATED AS ULT_FECHA 
FROM DBA_OBJECTS
WHERE OWNER = 'SCOTT'
ORDER BY CREATED DESC; 

--PREGUNTA 2
CREATE TABLE ALUMNOS(
	ID_ALUMNO INTEGER NOT NULL CONSTRAINT PK_ALUMNOS PRIMARY KEY,
	NOMBRE VARCHAR2(25),
	APELLIDO VARCHAR2(25),
	FECHA_NAC DATE
);

CREATE TABLE CURSOS(
	ID_CURSO INTEGER NOT NULL CONSTRAINT PK_CURSOS PRIMARY KEY,
	NOMBRE_CURSO VARCHAR2(25),
	CATEGORIA VARCHAR2(25) NOT NULL,
	DESCRIPCION VARCHAR2(25)
);

CREATE TABLE MATRICULA(
	ID_MATRICULA INTEGER CONSTRAINT NN_CATEGORIA NOT NULL PRIMARY KEY,
	ID_ALUMNO INTEGER NOT NULL,
	CONSTRAINT FK_MATRICULA_ALUMNOS FOREIGN KEY(ID_ALUMNO) REFERENCES ALUMNOS(ID_ALUMNO),
	ID_CURSO INTEGER NOT NULL,
	CONSTRAINT FK_MATRICULA_CURSOS FOREIGN KEY(ID_CURSO) REFERENCES CURSOS(ID_CURSO),
	FEC_MAT DATE
);

--PREGUNTA 3
--A
CREATE SEQUENCE SEQ_ALUMNOS 
MINVALUE 1
MAXVALUE 200
START WITH 100
INCREMENT BY 1 
CYCLE
NOCACHE;

--B
CREATE UNIQUE INDEX IDX_ALUM_NOMAP ON ALUMNOS(NOMBRE, APELLIDO);

--C
CREATE PUBLIC SYNONYM ALUM FOR SCOTT.ALUMNOS;

--PREGUNTA 4
--A
INSERT INTO ALUMNOS VALUES(SEQ_ALUMNOS.NEXTVAL,'JOSE','PEREZ','11/08/1984');
SELECT * FROM ALUMNOS;

--B
UPDATE ALUMNOS 
SET NOMBRE='JUAN' 
WHERE 
ID_ALUMNO=100;
SELECT * FROM ALUMNOS;

--C
DELETE FROM ALUMNOS WHERE 
ID_ALUMNO=100;
SELECT * FROM ALUMNOS;

--PREGUNTA 5
SELECT DEPT.DNAME AS DNAME, 'S/.'||ROUND(AVG(EMP.SAL),2) AS SAL_PROM
FROM 
DEPT INNER JOIN EMP ON DEPT.DEPTNO=EMP.DEPTNO
GROUP BY DEPT.DNAME  
ORDER BY DEPT.DNAME DESC;


--PREGUNTA 6
SELECT ENAME, 
RPAD(LPAD(SUBSTR(ENAME,TRUNC(LENGTH(ENAME)/2,0)+1,1),6,'*'),11,'*') AS "FORMATO SOLICITADO" 
FROM EMP
WHERE MOD(LENGTH(ENAME),2)=1;

--PREGUNTA 7
SELECT 
'HOY ES '|| TRIM(TO_CHAR(SYSDATE,'DAY'))||', '
||TRIM(TO_CHAR(SYSDATE,'DD'))||' de '
||TRIM(TO_CHAR(SYSDATE,'MONTH'))||' del '
||TRIM(TO_CHAR(SYSDATE,'YYYY'))
FROM DUAL;

--PREGUNTA 8
SELECT * FROM EMP;

SELECT 
ENAME, 
ROUND(POWER(MOD(SAL,3)/5,1/3),2) 
FROM EMP 
WHERE SAL>(SELECT SAL FROM EMP WHERE ENAME='CLARK');


--PREGUNTA 9
SELECT 
NEXT_DAY(SYSDATE,'DOMINGO')||' - ABRIGUENSE YA ESTA HACIENDO FRIO' 
FROM DUAL;
